### ISSUE TITLE
Offer finer ECC access lock control

### ISSUE THREAD

**Issue by mullerch** [helium/helium-crypto-rs#22]
If I understand correctly the implementation, the application using this library will lock the ECC (e.g. in case of an i2c access through the i2c dev driver), and this until the application is closed.

This is an issue, as the application (e.g. a daemon) may want to lock the device only when it has to use it. Otherwise it will prevent the use of the ECC to any other application.

This library should provide a way to access the ECC and free the ressources afterwards.

**Comment by hilt0n** [comment]
One solution could be to use the PKCS11 engine of OpenSSL and not access the ATECC directly. 
If possible, it would be way more cleaner but would add to the agent a system dependency on OpenSSL with cryptoauthlib support (which is well documented) and no more on i2c driver and atecc driver, a better platform support in the end since it splits cleanly the features and the hardware.

More information here: https://github.com/MicrochipTech/cryptoauthlib/wiki/PKCS11-Linux-Setup

With this solution, the Helium agent could probably call OpenSSL to encrypt data based on specific ATECC's slot.

Pros are a better integration with other tools who all use OpenSSL but then the Helium agent is less "turnkey solution".
Would be nice maybe to be able to chose between both solution from configuration files.

**Comment by madninja** [comment]
> One solution could be to use the PKCS11 engine of OpenSSL and not access the ATECC directly. If possible, it would be way more cleaner but would add to the agent a system dependency on OpenSSL with cryptoauthlib support (which is well documented) and no more on i2c driver and atecc driver, a better platform support in the end since it splits cleanly the features and the hardware.
> 
> More information here: https://github.com/MicrochipTech/cryptoauthlib/wiki/PKCS11-Linux-Setup
> 
> With this solution, the Helium agent could probably call OpenSSL to encrypt data based on specific ATECC's slot.
> 
> Pros are a better integration with other tools who all use OpenSSL but then the Helium agent is less "turnkey solution". Would be nice maybe to be able to chose between both solution from configuration files.

1. There is no consistent OpenSSL implementation across hardware platforms. So while this may work on servers its' been a real challenge on hotspots 
2. OpenSSL would still need to access the ECC and handle lock/unlock  scheduling between calls. 

The first one is the real dealbreaker here for using the openssl engine.

**Comment by mullerch** [comment]
> There is no consistent OpenSSL implementation across hardware platforms.

From Wikipedia:

> The PKCS #11 standard defines a platform-independent [API](https://en.wikipedia.org/wiki/Application_programming_interface) to [cryptographic tokens](https://en.wikipedia.org/wiki/Cryptographic_token), such as [hardware security modules](https://en.wikipedia.org/wiki/Hardware_security_module) (HSM) and [smart cards](https://en.wikipedia.org/wiki/Smart_cards)

To me it precisely provides a "consistent OpenSSL implementation". We should rather say interface, as the implementation is not very relevant. Not all platforms provide PCKS11, that's why it's a good idea to make it usable based on the configuration (either i2c or pcks11)

> OpenSSL would still need to access the ECC and handle lock/unlock scheduling between calls.

Of yourse. But this is not the issue. The issue is that the software locks the hardware event when not needed.

**Comment by madninja** [comment]
> > There is no consistent OpenSSL implementation across hardware platforms.
> 
> From Wikipedia:
> 
> > The PKCS #11 standard defines a platform-independent [API](https://en.wikipedia.org/wiki/Application_programming_interface) to [cryptographic tokens](https://en.wikipedia.org/wiki/Cryptographic_token), such as [hardware security modules](https://en.wikipedia.org/wiki/Hardware_security_module) (HSM) and [smart cards](https://en.wikipedia.org/wiki/Smart_cards)
> 
> To me it precisely provides a "consistent OpenSSL implementation". We should rather say interface, as the implementation is not very relevant. Not all platforms provide PCKS11, that's why it's a good idea to make it usable based on the configuration (either i2c or pcks11)
> 
> > OpenSSL would still need to access the ECC and handle lock/unlock scheduling between calls.
> 
> Of yourse. But this is not the issue. The issue is that the software locks the hardware event when not needed.

I very much agree. And would love to see a PR to make it so that fits on all embedded platforms gateway-rs needs to support. Since that hasn't happened since April this PR was closed. Does not mean it shouldn't happen though!
