### ISSUE TITLE
Improve PublicKey ParialOrd performance

### ISSUE THREAD

**Issue by JayKickliter** [helium/helium-crypto-rs#40]
For reasons lost to time perhaps, PublicKey's ParialOrd implementation performs **two** heap allocations. Sure this is bad, but is really that bad? It turns out yes. If you're using a public key as a tree data strucure key type, every step of the tree walks incurs at least one allocation for the in-tree node, and perhaps even an allocation for the key provided to `get()` if it's not optimized away.

**Comment by lthiery** [comment]
> @lthiery iirc you worked on PartialOrd here perhaps? Does ledger need public key ordering by their string representation?

Nope, I don't have any public key ordering by string representation. Thanks checking
